apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: message-sender-service
  labels:
    app: message-sender-service
spec:
  selector:
    app: message-sender
  ports:
    - port: 5000 # The port that the service is running on in the cluster
      nodePort: 30100 # Port accessible outside cluster
      name: http
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: message-sender
spec:
  selector:
    matchLabels:
      app: message-sender
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: survival-curve
    spec:
      containers:
        - image: azdrojowa123/message-sender:latest
          imagePullPolicy: IfNotPresent
          name: survival-curve
          ports:
            - containerPort: 5000 # The port that the container is running on in the cluster
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: csv-validator-logistic-regression
spec:
  selector:
    matchLabels:
      app: csv-validator-logistic-regression
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: csv-validator-lr
    spec:
      containers:
        - image: azdrojowa123/csv-validator-logistic-regression:latest
          imagePullPolicy: IfNotPresent
          name: csv-validator-lr
          ports:
            - containerPort: 5001 # The port that the container is running on in the cluster
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: csv-validator-logistic-regression
spec:
  selector:
    matchLabels:
      app: csv-validator-logistic-regression
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: csv-validator-lr
    spec:
      containers:
        - image: azdrojowa123/csv-validator-logistic-regression:latest
          imagePullPolicy: IfNotPresent
          name: csv-validator-lr
          ports:
            - containerPort: 5001 # The port that the container is running on in the cluster