apiVersion: v1
kind: Service
metadata:
  name: message-sender-service
  labels:
    app: message-sender-service
spec:
  selector:
    app: message-sender
  ports:
    - port: 5000
      nodePort: 30100
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
spec:
  selector:
    matchLabels:
      app: message-sender
  replicas: 1
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
        - image: azdrojowa123/message-sender:2.3
          imagePullPolicy: Always
          name: message-sender
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "90m"
            limits:
              cpu: "150m"

---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: csv-validator-logistic-regression
spec:
  selector:
    matchLabels:
      app: csv-validator-lr
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: csv-validator-lr
    spec:
      containers:
        - image: azdrojowa123/csv-validator-logistic-regression:2.3
          imagePullPolicy: Always
          name: csv-validator-lr
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5001 # The port that the container is running on in the cluster
          resources:
            requests:
              cpu: "90m" # 1core = 1000 milicores = 1000 m
            limits:
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-regression-calc
spec:
  selector:
    matchLabels:
      app: logistic-regression-calc
  replicas: 1
  template:
    metadata:
      labels:
        app: logistic-regression-calc
    spec:
      containers:
        - image: azdrojowa123/logistic-regression-calc:2.3
          imagePullPolicy: Always
          name: logistic-regression-calc
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "90m"
            limits:
              cpu: "150m"
---
apiVersion: v1
kind: Secret
metadata:
  name: logistic-regression-secret
type: Opaque
data:
  DbPassword: cm9vdA==

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: message-sender-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: message-sender
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 30

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: logistic-regression-calc-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: logistic-regression-calc
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 30

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: csv-validator-lr-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: csv-validator-logistic-regression
  minReplicas: 1
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 20