apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: message-sender-service
  labels:
    app: message-sender-service
spec:
  selector:
    app: message-sender
  ports:
    - port: 5000 # The port that the service is running on in the cluster
      nodePort: 30100 # Port accessible outside cluster
      name: http
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: message-sender
spec:
  selector:
    matchLabels:
      app: message-sender
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
        - image: azdrojowa123/message-sender:latest
          imagePullPolicy: Always
          name: message-sender
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5000 # The port that the container is running on in the cluster
          resources:
            requests:
              memory: "120Mi" # 1GiB=1024^3=1024MiB=1024Mi
              cpu: "100m" # 1core = 1000 milicores = 1000 m
            limits:
              memory: "140Mi"
              cpu: "150m"

---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: csv-validator-logistic-regression
spec:
  selector:
    matchLabels:
      app: csv-validator-lr
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: csv-validator-lr
    spec:
      containers:
        - image: azdrojowa123/csv-validator-logistic-regression:latest
          imagePullPolicy: IfNotPresent
          name: csv-validator-lr
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5001 # The port that the container is running on in the cluster
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: logistic-regression-calc
spec:
  selector:
    matchLabels:
      app: logistic-regression-calc
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: logistic-regression-calc
    spec:
      containers:
        - image: azdrojowa123/logistic-regression-calc:latest
          imagePullPolicy: IfNotPresent
          name: logistic-regression-calc
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistic-regression-secret
                  key: DbPassword
          ports:
            - containerPort: 5002 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: logistic-regression-secret
type: Opaque
data:
  DbPassword: cm9vdA==

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: message-sender-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: message-sender
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
