apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: survival-curve-service
  labels:
    app: survival-curve-service
spec:
  selector:
    app: survival-curve
  ports:
    - port: 8080 # The port that the service is running on in the cluster
      nodePort: 30001 # Port accessible outside cluster
      name: http
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: csv-validator-service
  labels:
    app: csv-validator-service
spec:
  selector:
    app: csv-validator-sc
  ports:
    - port: 8081 # The port that the service is running on in the cluster
      nodePort: 30002 # Port accessible outside cluster
      name: http
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: survival-curve
spec:
  selector:
    matchLabels:
      app: survival-curve
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: survival-curve
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: azdrojowa123/survival-curve-calc:2.8
          imagePullPolicy: IfNotPresent
          name: survival-curve
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          startupProbe:
            httpGet:
              path: /readiness/probe
              port: 8080
            timeoutSeconds: 3
            failureThreshold: 300
            periodSeconds: 2
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: csv-validator-survival-curve
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector: # must be 1 pod with this label created
    matchLabels:
      app: csv-validator-sc
  template: # how to create Pod
    metadata:
      labels:
        app: csv-validator-sc
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: azdrojowa123/csv-validator-survival-curve:2.9
          imagePullPolicy: IfNotPresent
          name: csv-validator-sc
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /readiness/probe
              port: 8081
            timeoutSeconds: 3
            failureThreshold: 300
            periodSeconds: 2
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: survival-curve-calc-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: survival-curve
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 35

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: csv-validator-survival-curve-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: csv-validator-survival-curve
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 40